apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: logging
spec:
  version: 7.16.2 
  ports:
    - containerPort: 9200
      name: http
      protocol: TCP
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: logging
  labels:
    service: elasticsearch
spec:
  type: NodePort  
  ports:
  - port: 9200
    targetPort: 9200
    nodePort: 32200


