apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  namespace: monitoring
spec:
  selector:
    app: influxdb
  type: NodePort
  ports:
    - name: api
      port: 9999
    - name: gui
      port: 8086
      targetPort: 8086
      nodePort: 31234